### ISSUE TITLE
Formatting + Qualitative descriptions - new branch

### ISSUE THREAD

**Issue by rashiselarka** [DSCI-310-2024/DSCI_310_Group_9_NY-airbnb-analysis#17]
Changes being made:

- Deleted `dsci.yml` (duplicate of `environment.yml`)
- Formatting of `milestone_1.ipynb` - sections, fig. numbers, fig. sizes
- Fleshing out introduction, and any descriptive chunks
- Adding references

**Comment by riddhibattu** [comment]
done
