### ISSUE TITLE
Tests for data preprocessing

### ISSUE THREAD

**Issue by rashiselarka** [DSCI-310-2024/DSCI_310_Group_9_NY-airbnb-analysis#39]

**Comment by riddhibattu** [comment]
I have added test function for the main 2 scripts for data import and preprocessing along with tests for the function I created. [test_add-price-category.py](https://github.com/DSCI-310-2024/DSCI_310_Group_9_NY-airbnb-analysis/blob/main/tests/test_add-price-category.py), [test_data-preprocessing.py](https://github.com/DSCI-310-2024/DSCI_310_Group_9_NY-airbnb-analysis/blob/main/tests/test_data-preprocessing.py) and [test_get-data.py](https://github.com/DSCI-310-2024/DSCI_310_Group_9_NY-airbnb-analysis/blob/main/tests/test_get-data.py)
