### ISSUE TITLE
implement feedback from milestone 2 and peer review

### ISSUE THREAD

**Issue by rashiselarka** [DSCI-310-2024/DSCI_310_Group_9_NY-airbnb-analysis#59]

**Comment by riddhibattu** [comment]
https://github.com/DSCI-310-2024/data-analysis-review-2024/issues/9

We have removed the .local files and the ones not needed.

**Comment by riddhibattu** [comment]
Done

**Comment by riddhibattu** [comment]
Added DOI as recommended
